### ISSUE TITLE
Sources of missing data in the index output

### ISSUE THREAD

**Issue by FlowerDance916** [jamesjiadazhan/dietaryindex_NHANES#2]
I recently tried to reproduce this article (DOI: 10.1002/hep.32207). However, our inclusion-exclusion processes differed significantly in the meals section. We both used HEI 2015, and this article excluded over 300 cases of missing values, while I excluded over 700 cases. Therefore, I wonder about the source of the missing values in the direct exclusion of HEI2015 and even the rest of the indexes and whether it is correct to exclude the missing values in HEI2015 directly.

**Comment by jamesjiadazhan** [comment]
I tried to look at it and it is hard to tell whether your missing value method is the same as that article. It would be more clear if you could share how you excluded missing values in the HEI2015 and how they did it. Also, you should explore if they use 1-day or 2-day dietary data from NHANES. HEI2015_NHANES_FPED function produces the exact same results as the NCI's SAS code, so it has to be something relate to the difference of the data inclusion for HEI2015 and data exclusion for missing values.

**Comment by FlowerDance916** [comment]
Thank you for your prompt reply! I use HEI2015_NHANES_FPED function to calculate HEI2015 and remove all the NA as missing values. That study included participants who completed two 24-hour dietary recalls. So, I think they might misuse 1-day dietary data in their analysis, excluding fewer participants. I have almost finished my analysis and will cite your hard work in my paper.

**Comment by jamesjiadazhan** [comment]
A quick way to check this is to do a one day 24-hour dietary recall and see the number of excluded data. Sometimes researchers make mistakes in dietary index calculation, and that's one of the reasons why dietaryindex is created.

Thank you for using dietaryindex and citing our work! Let me know if you have other questions.
